<?php

namespace Infrastructure\FrameworkCore\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;
use Infrastructure\FrameworkCore\Registry\ActionRegistry;
use Infrastructure\FrameworkCore\Registry\EntityRegistry;

/**
 * Caches the entity/action registry map to a static PHP file.
 * This eliminates the filesystem scan and reflection overhead on every request.
 *
 * Usage:
 *   php artisan core:cache          → Build the cache
 *   php artisan core:cache --clear  → Delete the cache
 */
class CoreCacheCommand extends Command
{
    protected $signature = 'core:cache {--clear : Clear the metadata cache}';

    protected $description = 'Cache the BOUNDLY metadata registry for high-performance production use.';

    public function __construct(
        protected EntityRegistry $entityRegistry,
        protected ActionRegistry $actionRegistry
    ) {
        parent::__construct();
    }

    public function handle(): void
    {
        $cachePath = $this->getCachePath();

        if ($this->option('clear')) {
            if (File::exists($cachePath)) {
                File::delete($cachePath);
                $this->info('✅ BOUNDLY metadata cache cleared.');
            } else {
                $this->warn('No cache file found.');
            }

            return;
        }

        $this->info('🔍 Scanning Domain and Application layers...');

        // The registries have already been populated during boot.
        // We just serialize the final map to disk.
        $entities = $this->entityRegistry->getAllEntities();
        $actions = $this->actionRegistry->getAllActions();

        // Serialize to a plain PHP array (fast require, no JSON parsing)
        $export = var_export([
            'entities' => $entities,
            'actions' => $actions,
            'built_at' => now()->toISOString(),
        ], true);

        $content = "<?php\n\n// Auto-generated by BOUNDLY core:cache. Do not edit.\nreturn {$export};\n";

        File::ensureDirectoryExists(dirname($cachePath));
        File::put($cachePath, $content);

        $this->info('✅ BOUNDLY metadata cached successfully.');
        $this->line("   Path    : {$cachePath}");
        $this->line('   Entities: '.count($entities));
        $this->line('   Actions : '.count($actions));
        $this->newLine();
        $this->warn('⚠  Run `php artisan core:cache --clear` after any Domain/Application changes.');
    }

    public static function getCachePath(): string
    {
        return base_path('bootstrap/cache/boundly.php');
    }
}
