<?php

namespace Infrastructure\FrameworkCore\Console\Commands;

use Illuminate\Console\Command;
use Infrastructure\FrameworkCore\Registry\EntityRegistry;
use Infrastructure\FrameworkCore\Registry\ActionRegistry;
use Illuminate\Support\Facades\File;

/**
 * Generates an OpenAPI 3.0 (Swagger) specification file automatically
 * from the Entity and Action registries — no manual documentation needed.
 *
 * Usage:
 *   php artisan core:docs              → Output to storage/app/openapi.json
 *   php artisan core:docs --format=yaml
 */
class CoreDocCommand extends Command
{
    protected $signature   = 'core:docs {--format=json : Output format: json or yaml} {--out= : Custom output path}';
    protected $description = 'Auto-generate OpenAPI 3.0 documentation from Domain entities and Application actions.';

    // Maps BOUNDLY column types to OpenAPI types
    private const TYPE_MAP = [
        'string'             => ['type' => 'string'],
        'email'              => ['type' => 'string', 'format' => 'email'],
        'integer'            => ['type' => 'integer', 'format' => 'int64'],
        'bigInteger'         => ['type' => 'integer', 'format' => 'int64'],
        'tinyInteger'        => ['type' => 'integer'],
        'float'              => ['type' => 'number', 'format' => 'float'],
        'double'             => ['type' => 'number', 'format' => 'double'],
        'decimal'            => ['type' => 'number'],
        'boolean'            => ['type' => 'boolean'],
        'date'               => ['type' => 'string', 'format' => 'date'],
        'datetime'           => ['type' => 'string', 'format' => 'date-time'],
        'timestamp'          => ['type' => 'string', 'format' => 'date-time'],
        'json'               => ['type' => 'object'],
        'text'               => ['type' => 'string'],
        'longText'           => ['type' => 'string'],
    ];

    public function __construct(
        protected EntityRegistry $entityRegistry,
        protected ActionRegistry $actionRegistry
    ) {
        parent::__construct();
    }

    public function handle(): void
    {
        $this->info('📄 Generating OpenAPI 3.0 documentation...');

        $spec = [
            'openapi' => '3.0.3',
            'info'    => [
                'title'       => config('app.name', 'BOUNDLY API'),
                'version'     => config('app.version', '1.0.0'),
                'description' => 'Auto-generated by the BOUNDLY Framework engine.',
            ],
            'servers'    => [['url' => config('app.url') . '/' . config('boundly.api_prefix', 'api')]],
            'paths'      => [],
            'components' => ['schemas' => []],
        ];

        foreach ($this->entityRegistry->getAllEntities() as $resource => $config) {
            $schemaName = $this->toSchemaName($config['class']);
            $spec['components']['schemas'][$schemaName] = $this->buildSchema($config);

            $spec['paths']["/{$resource}"]        = $this->buildCollectionPaths($resource, $schemaName, $config);
            $spec['paths']["/{$resource}/{id}"]   = $this->buildResourcePaths($resource, $schemaName, $config);
        }

        $outputPath = $this->option('out') ?: storage_path('app/openapi.json');
        File::ensureDirectoryExists(dirname($outputPath));
        File::put($outputPath, json_encode($spec, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES));

        $this->info("✅ Documentation generated.");
        $this->line("   File: {$outputPath}");
        $this->line("   You can view it at: https://editor.swagger.io");
    }

    private function buildSchema(array $config): array
    {
        $properties = [
            $config['primaryKey'] => ['type' => 'integer', 'format' => 'int64', 'readOnly' => true],
        ];
        $required = [];

        foreach ($config['columns'] as $colName => $colAttr) {
            $typeInfo = self::TYPE_MAP[$colAttr->type] ?? ['type' => 'string'];

            $prop = $typeInfo;
            if ($colAttr->length) {
                $prop['maxLength'] = $colAttr->length;
            }
            if ($colAttr->default !== null) {
                $prop['default'] = $colAttr->default;
            }
            if ($colAttr->nullable) {
                $prop['nullable'] = true;
            }

            // Mark as hidden (write-only) if the field is in hidden list
            if (in_array($colName, $config['hidden'])) {
                $prop['writeOnly'] = true;
            }

            $properties[$colName] = $prop;

            if (!$colAttr->nullable && $colAttr->default === null) {
                $required[] = $colName;
            }
        }

        $schema = [
            'type'       => 'object',
            'properties' => $properties,
        ];

        if (!empty($required)) {
            $schema['required'] = $required;
        }

        return $schema;
    }

    private function buildCollectionPaths(string $resource, string $schemaName, array $config): array
    {
        $paths = [];

        // GET /resource (list)
        $paths['get'] = [
            'tags'        => [$resource],
            'summary'     => "List all {$resource}",
            'operationId' => "list_{$resource}",
            'parameters'  => [
                ['name' => 'page',     'in' => 'query', 'schema' => ['type' => 'integer']],
                ['name' => 'per_page', 'in' => 'query', 'schema' => ['type' => 'integer', 'default' => 15]],
                ['name' => 'include',  'in' => 'query', 'description' => 'Comma-separated relations to include', 'schema' => ['type' => 'string']],
            ],
            'responses' => [
                '200' => $this->paginatedResponse($schemaName),
            ],
        ];

        // POST /resource
        $paths['post'] = [
            'tags'        => [$resource],
            'summary'     => "Create a new {$resource}",
            'operationId' => "create_{$resource}",
            'requestBody' => $this->requestBody($schemaName),
            'responses'   => [
                '201' => $this->singleResponse($schemaName),
                '422' => $this->validationErrorResponse(),
            ],
        ];

        return $paths;
    }

    private function buildResourcePaths(string $resource, string $schemaName, array $config): array
    {
        $idParam = [
            'name'     => 'id',
            'in'       => 'path',
            'required' => true,
            'schema'   => ['type' => 'integer'],
        ];

        return [
            'get' => [
                'tags'        => [$resource],
                'summary'     => "Get a {$resource} by ID",
                'operationId' => "show_{$resource}",
                'parameters'  => [$idParam],
                'responses'   => ['200' => $this->singleResponse($schemaName), '404' => $this->notFoundResponse()],
            ],
            'put' => [
                'tags'        => [$resource],
                'summary'     => "Replace a {$resource}",
                'operationId' => "replace_{$resource}",
                'parameters'  => [$idParam],
                'requestBody' => $this->requestBody($schemaName),
                'responses'   => ['200' => $this->singleResponse($schemaName), '422' => $this->validationErrorResponse()],
            ],
            'patch' => [
                'tags'        => [$resource],
                'summary'     => "Update a {$resource} partially",
                'operationId' => "update_{$resource}",
                'parameters'  => [$idParam],
                'requestBody' => $this->requestBody($schemaName),
                'responses'   => ['200' => $this->singleResponse($schemaName), '422' => $this->validationErrorResponse()],
            ],
            'delete' => [
                'tags'        => [$resource],
                'summary'     => "Delete a {$resource}",
                'operationId' => "delete_{$resource}",
                'parameters'  => [$idParam],
                'responses'   => ['200' => ['description' => 'Deleted successfully.']],
            ],
        ];
    }

    private function toSchemaName(string $className): string
    {
        return class_basename($className);
    }

    private function requestBody(string $schemaName): array
    {
        return [
            'required' => true,
            'content'  => ['application/json' => ['schema' => ['$ref' => "#/components/schemas/{$schemaName}"]]],
        ];
    }

    private function singleResponse(string $schemaName): array
    {
        return [
            'description' => 'Successful operation',
            'content'     => ['application/json' => ['schema' => [
                'type'       => 'object',
                'properties' => [
                    'status' => ['type' => 'string', 'example' => 'success'],
                    'data'   => ['$ref' => "#/components/schemas/{$schemaName}"],
                ],
            ]]],
        ];
    }

    private function paginatedResponse(string $schemaName): array
    {
        return [
            'description' => 'Paginated list',
            'content'     => ['application/json' => ['schema' => [
                'type'       => 'object',
                'properties' => [
                    'status' => ['type' => 'string'],
                    'data'   => ['type' => 'array', 'items' => ['$ref' => "#/components/schemas/{$schemaName}"]],
                    'meta'   => [
                        'type'       => 'object',
                        'properties' => [
                            'current_page' => ['type' => 'integer'],
                            'last_page'    => ['type' => 'integer'],
                            'per_page'     => ['type' => 'integer'],
                            'total'        => ['type' => 'integer'],
                        ],
                    ],
                ],
            ]]],
        ];
    }

    private function validationErrorResponse(): array
    {
        return ['description' => 'Validation failed (422 Unprocessable Entity)'];
    }

    private function notFoundResponse(): array
    {
        return ['description' => 'Resource not found (404)'];
    }
}
