<?php

namespace Infrastructure\FrameworkCore\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;
use Infrastructure\FrameworkCore\Attributes\UseCase\Action;
use Infrastructure\FrameworkCore\Registry\ActionRegistry;
use Infrastructure\FrameworkCore\Registry\EntityRegistry;

/**
 * Generates an OpenAPI 3.0 (Swagger) specification file automatically
 * from the Entity and Action registries — no manual documentation needed.
 *
 * Usage:
 *   php artisan core:docs              → Output to storage/app/openapi.json
 *   php artisan core:docs --format=yaml
 */
class CoreDocCommand extends Command
{
    protected $signature = 'core:docs {--format=json : Output format: json or yaml} {--out= : Custom output path}';

    protected $description = 'Auto-generate OpenAPI 3.0 documentation from Domain entities and Application actions.';

    private const TYPE_MAP = [
        'string' => ['type' => 'string'],
        'email' => ['type' => 'string', 'format' => 'email'],
        'integer' => ['type' => 'integer', 'format' => 'int64'],
        'bigInteger' => ['type' => 'integer', 'format' => 'int64'],
        'tinyInteger' => ['type' => 'integer'],
        'float' => ['type' => 'number', 'format' => 'float'],
        'double' => ['type' => 'number', 'format' => 'double'],
        'decimal' => ['type' => 'number'],
        'boolean' => ['type' => 'boolean'],
        'date' => ['type' => 'string', 'format' => 'date'],
        'datetime' => ['type' => 'string', 'format' => 'date-time'],
        'timestamp' => ['type' => 'string', 'format' => 'date-time'],
        'json' => ['type' => 'object'],
        'text' => ['type' => 'string'],
        'longText' => ['type' => 'string'],
    ];

    private const DEFAULT_CRUD_METHODS = ['GET', 'POST', 'PUT', 'PATCH', 'DELETE'];

    public function __construct(
        protected EntityRegistry $entityRegistry,
        protected ActionRegistry $actionRegistry
    ) {
        parent::__construct();
    }

    public function handle(): void
    {
        $this->info('📄 Generating OpenAPI 3.0 documentation...');

        $spec = [
            'openapi' => '3.0.3',
            'info' => [
                'title' => 'BOUNDLY API',
                'version' => '0.9.0',
                'description' => 'Auto-generated by the BOUNDLY Framework. Define your Domain. BOUNDLY handles the rest.',
            ],
            'servers' => [['url' => config('app.url', 'http://localhost').'/'.config('boundly.api_prefix', 'api')]],
            'paths' => [],
            'components' => ['schemas' => []],
        ];

        $registeredActions = $this->actionRegistry->getAllActions();

        foreach ($this->entityRegistry->getAllEntities() as $resource => $config) {
            $schemaName = $this->toSchemaName($config['class']);
            $spec['components']['schemas'][$schemaName] = $this->buildSchema($config);

            $spec['paths']["/{$resource}"] = $this->buildCollectionPaths($resource, $schemaName, $config, $registeredActions);
            $spec['paths']["/{$resource}/{id}"] = $this->buildResourcePaths($resource, $schemaName, $config, $registeredActions);
        }

        foreach ($registeredActions as $key => $actionClass) {
            [$method, $actionResource] = explode('_', $key, 2) + [1 => null];
            $method = strtolower($method);

            if ($actionResource && ! $this->entityRegistry->getEntityConfig($actionResource)) {
                $spec['paths']["/{$actionResource}"] = $this->buildCustomActionPath($actionResource, $method, $actionClass);
            }
        }

        $outputPath = $this->option('out') ?: storage_path('app/openapi.json');
        File::ensureDirectoryExists(dirname($outputPath));
        File::put($outputPath, json_encode($spec, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES));

        $entityCount = count($this->entityRegistry->getAllEntities());
        $actionCount = count($registeredActions);

        $this->info('✅ Documentation generated.');
        $this->line("   File: {$outputPath}");
        $this->line("   Entities: {$entityCount} | Actions: {$actionCount}");
        $this->line('');
        $this->line('   📖 Visual preview:');
        $this->line('   → https://editor.swagger.io (paste JSON content)');
        $this->line('');
        $port = config('app.port', 8000);
        $baseUrl = config('app.url', 'http://localhost');
        $url = str_replace(['http://', 'https://'], '', $baseUrl);
        $fullUrl = "{$url}:{$port}";

        $this->info('   📭 Import in Postman/Insomnia:');
        $this->line("   1. Run 'php artisan core:watch' to start development");
        $this->line("   2. Import JSON: Postman → Import → File → upload '{$outputPath}'");
        $this->line("   3. Set variable: In your collection, add '{{baseUrl}}' = '{$fullUrl}'");
    }

    private function buildSchema(array $config): array
    {
        $properties = [
            $config['primaryKey'] => ['type' => 'integer', 'format' => 'int64', 'readOnly' => true],
        ];
        $required = [];

        foreach ($config['columns'] as $colName => $colAttr) {
            $typeInfo = self::TYPE_MAP[$colAttr->type] ?? ['type' => 'string'];

            $prop = $typeInfo;
            if ($colAttr->length) {
                $prop['maxLength'] = $colAttr->length;
            }
            if ($colAttr->default !== null) {
                $prop['default'] = $colAttr->default;
            }
            if ($colAttr->nullable) {
                $prop['nullable'] = true;
            }

            if (in_array($colName, $config['hidden'])) {
                $prop['writeOnly'] = true;
            }

            $properties[$colName] = $prop;

            if (! $colAttr->nullable && $colAttr->default === null) {
                $required[] = $colName;
            }
        }

        $schema = [
            'type' => 'object',
            'properties' => $properties,
        ];

        if (! empty($required)) {
            $schema['required'] = $required;
        }

        return $schema;
    }

    private function buildCollectionPaths(string $resource, string $schemaName, array $config, array $registeredActions): array
    {
        $paths = [];

        $getActionKey = 'GET_'.$resource;
        $postActionKey = 'POST_'.$resource;

        $getIsCustom = isset($registeredActions[$getActionKey]);
        $postIsCustom = isset($registeredActions[$postActionKey]);

        $paths['get'] = [
            'tags' => [$resource],
            'summary' => $getIsCustom ? "Custom by actions: List all {$resource}" : "List all {$resource}",
            'description' => $getIsCustom ? '**CUSTOM ACTION** - Overrides default CRUD behavior' : null,
            'operationId' => "list_{$resource}",
            'parameters' => [
                ['name' => 'page', 'in' => 'query', 'schema' => ['type' => 'integer']],
                ['name' => 'per_page', 'in' => 'query', 'schema' => ['type' => 'integer', 'default' => 15]],
                ['name' => 'include', 'in' => 'query', 'description' => 'Comma-separated relations to include', 'schema' => ['type' => 'string']],
            ],
            'responses' => [
                '200' => $this->paginatedResponse($schemaName),
            ],
        ];

        $paths['post'] = [
            'tags' => [$resource],
            'summary' => $postIsCustom ? "Custom by actions: Create a new {$resource}" : "Create a new {$resource}",
            'description' => $postIsCustom ? '**CUSTOM ACTION** - Overrides default CRUD behavior' : null,
            'operationId' => "create_{$resource}",
            'requestBody' => $this->requestBody($schemaName),
            'responses' => [
                '201' => $this->singleResponse($schemaName),
                '422' => $this->validationErrorResponse(),
            ],
        ];

        return array_filter($paths, fn ($v) => $v !== null);
    }

    private function buildResourcePaths(string $resource, string $schemaName, array $config, array $registeredActions): array
    {
        $idParam = [
            'name' => 'id',
            'in' => 'path',
            'required' => true,
            'schema' => ['type' => 'integer'],
        ];

        $paths = [];
        $methods = ['get', 'put', 'patch', 'delete'];

        foreach ($methods as $method) {
            $actionKey = strtoupper($method).'_'.$resource;
            $isCustom = isset($registeredActions[$actionKey]);

            $methodConfig = match ($method) {
                'get' => [
                    'summary' => $isCustom ? "Custom by actions: Get a {$resource} by ID" : "Get a {$resource} by ID",
                    'operationId' => "show_{$resource}",
                    'responses' => ['200' => $this->singleResponse($schemaName), '404' => $this->notFoundResponse()],
                ],
                'put' => [
                    'summary' => $isCustom ? "Custom by actions: Replace a {$resource}" : "Replace a {$resource}",
                    'operationId' => "replace_{$resource}",
                    'responses' => ['200' => $this->singleResponse($schemaName), '422' => $this->validationErrorResponse()],
                ],
                'patch' => [
                    'summary' => $isCustom ? "Custom by actions: Update a {$resource} partially" : "Update a {$resource} partially",
                    'operationId' => "update_{$resource}",
                    'responses' => ['200' => $this->singleResponse($schemaName), '422' => $this->validationErrorResponse()],
                ],
                'delete' => [
                    'summary' => $isCustom ? "Custom by actions: Delete a {$resource}" : "Delete a {$resource}",
                    'operationId' => "delete_{$resource}",
                    'responses' => ['204' => ['description' => 'Deleted successfully. (No Content)']],
                ],
            };

            $paths[$method] = [
                'tags' => [$resource],
                'summary' => $methodConfig['summary'],
                'description' => $isCustom ? '**CUSTOM ACTION** - Overrides default CRUD behavior' : null,
                'operationId' => $methodConfig['operationId'],
                'parameters' => [$idParam],
                'responses' => $methodConfig['responses'],
            ];

            if ($method !== 'delete') {
                $paths[$method]['requestBody'] = $this->requestBody($schemaName);
            }
        }

        return $paths;
    }

    private function buildCustomActionPath(string $resource, string $method, string $actionClass): array
    {
        $reflection = new \ReflectionClass($actionClass);
        $attributes = $reflection->getAttributes(Action::class);
        $actionAttr = $attributes[0]->newInstance();

        $desc = $actionAttr->resource !== $resource
            ? "Custom action on resource '{$actionAttr->resource}' → '{$resource}'"
            : "Custom action on resource '{$resource}'";

        return [
            strtolower($method) => [
                'tags' => [$resource],
                'summary' => "Custom by actions: {$resource} ({$method})",
                'description' => "**CUSTOM ACTION** - {$desc}\n\nClass: `{$actionClass}`",
                'operationId' => "custom_{$method}_{$resource}",
                'responses' => ['200' => ['description' => 'Custom action response']],
            ],
        ];
    }

    private function toSchemaName(string $className): string
    {
        return class_basename($className);
    }

    private function requestBody(string $schemaName): array
    {
        return [
            'required' => true,
            'content' => ['application/json' => ['schema' => ['$ref' => "#/components/schemas/{$schemaName}"]]],
        ];
    }

    private function singleResponse(string $schemaName): array
    {
        return [
            'description' => 'Successful operation',
            'content' => ['application/json' => ['schema' => [
                'type' => 'object',
                'properties' => [
                    'status' => ['type' => 'string', 'example' => 'success'],
                    'data' => ['$ref' => "#/components/schemas/{$schemaName}"],
                ],
            ]]],
        ];
    }

    private function paginatedResponse(string $schemaName): array
    {
        return [
            'description' => 'Paginated list',
            'content' => ['application/json' => ['schema' => [
                'type' => 'object',
                'properties' => [
                    'status' => ['type' => 'string'],
                    'data' => ['type' => 'array', 'items' => ['$ref' => "#/components/schemas/{$schemaName}"]],
                    'meta' => [
                        'type' => 'object',
                        'properties' => [
                            'current_page' => ['type' => 'integer'],
                            'last_page' => ['type' => 'integer'],
                            'per_page' => ['type' => 'integer'],
                            'total' => ['type' => 'integer'],
                        ],
                    ],
                ],
            ]]],
        ];
    }

    private function validationErrorResponse(): array
    {
        return ['description' => 'Validation failed (422 Unprocessable Entity)'];
    }

    private function notFoundResponse(): array
    {
        return ['description' => 'Resource not found (404)'];
    }
}
