<?php

namespace Application\Users\Actions;

use Domain\Users\Entities\User;
use Domain\Users\Entities\Profile;
use Domain\Posts\Entities\Post;
use Infrastructure\FrameworkCore\Attributes\Action;
use Infrastructure\FrameworkCore\Database\DynamicRepository;
use Application\Users\DTOs\CreateUserDTO;
use Illuminate\Support\Facades\Event;
use Illuminate\Support\Facades\DB;

#[Action(resource: 'users', method: 'POST')]
class CreateUserWithProfile
{
    public function __construct(protected DynamicRepository $repository) {}

    public function execute(CreateUserDTO $dto)
    {
        return DB::transaction(function () use ($dto) {
            // 1. Instantiate PURE Domain Entity
            $user = new User(
                $dto->name, 
                $dto->email, 
                $dto->password
            );

            // 2. Persist the User (Using repository for Timestamps & Audit)
            $userData = [
                'name' => $user->getName(),
                'email' => $user->getEmail(),
                'password' => $user->getPassword(),
                'phone' => $dto->phone,
                'addres' => $dto->addres,
            ];

            $savedUser = $this->repository->insert('users', $userData);
            $userId = $savedUser['id'];

            // 3. Create related Profile (Mandatory business rule)
            $profile = new Profile(
                $dto->avatar_url ?? 'default_avatar.png',
                $dto->bio ?? 'Hello! I am a new user.',
                $userId
            );

            $this->repository->insert('profiles', [
                'avatar_url' => $profile->getAvatarUrl(),
                'bio' => $profile->getBio(),
                'user_id' => $profile->getUserId()
            ]);

            // 4. Create Welcome Post (Mandatory business rule)
            $welcomePost = new Post(
                "Welcome to my wall!",
                "This is my first automatic post generated by the BOUNDLY Framework.",
                $userId
            );

            $this->repository->insert('posts', [
                'title' => $welcomePost->getTitle(),
                'content' => $welcomePost->getContent(),
                'user_id' => $welcomePost->getUserId()
            ]);

            // 5. Release Domain Events
            foreach ($user->releaseEvents() as $event) {
                Event::dispatch($event);
            }

            return [
                'user_id' => $userId, 
                'status' => 'Full User Structure Created (User + Profile + Welcome Post)'
            ];
        });
    }
}
